/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store.view.admin;

import store.view.admin.profile.*;
import store.view.admin.revenue.*;
import store.view.admin.user.*;

/**
 *
 * @author bourbon
 */
public class MainAdmin extends javax.swing.JFrame {
        private Profile Profile;
        private Revenue Revenue;
        private ManagerUser managerUser;

        /**
         * Creates new form MainAdmin
         */
        public MainAdmin() {
                initComponents();
                this.setLocationRelativeTo(null);

                Profile = new Profile();
                this.add(Profile);
                Profile.setBounds(260, 80, 1250, 650);

                Revenue = new Revenue();
                this.add(Revenue);
                Revenue.setBounds(260, 80, 1250, 650);

                managerUser = new ManagerUser();
                this.add(managerUser);
                managerUser.setBounds(260, 80, 1250, 650);

                Revenue.setVisible(true);
                Profile.setVisible(true);
                managerUser.setVisible(true);

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                Navbar = new javax.swing.JPanel();
                UserButton = new javax.swing.JButton();
                RevenueButton = new javax.swing.JButton();
                SignOutButton = new javax.swing.JButton();
                UpdateInfoButton = new javax.swing.JButton();
                HeaderPanel = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("MainAdmin");

                Navbar.setBackground(new java.awt.Color(204, 204, 204));

                UserButton.setText("User Management");
                UserButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                UserButtonActionPerformed(evt);
                        }
                });

                RevenueButton.setText("Revenue");
                RevenueButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RevenueButtonActionPerformed(evt);
                        }
                });

                SignOutButton.setText("Sign Out");
                SignOutButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SignOutButtonActionPerformed(evt);
                        }
                });

                UpdateInfoButton.setText("Update Info");
                UpdateInfoButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                UpdateInfoButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
                Navbar.setLayout(NavbarLayout);
                NavbarLayout.setHorizontalGroup(
                                NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(NavbarLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(NavbarLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(UserButton,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(RevenueButton,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                225, Short.MAX_VALUE)
                                                                                .addComponent(SignOutButton,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                225,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap())
                                                .addGroup(NavbarLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(NavbarLayout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(UpdateInfoButton,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                225,
                                                                                                Short.MAX_VALUE)
                                                                                .addContainerGap())));
                NavbarLayout.setVerticalGroup(
                                NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(NavbarLayout.createSequentialGroup()
                                                                .addGap(247, 247, 247)
                                                                .addComponent(UserButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                46,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(RevenueButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                46,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(SignOutButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                46,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(347, Short.MAX_VALUE))
                                                .addGroup(NavbarLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(NavbarLayout.createSequentialGroup()
                                                                                .addGap(195, 195, 195)
                                                                                .addComponent(UpdateInfoButton,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                46,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap(498,
                                                                                                Short.MAX_VALUE))));

                HeaderPanel.setBackground(new java.awt.Color(153, 153, 153));
                HeaderPanel.setToolTipText("Header");

                javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
                HeaderPanel.setLayout(HeaderPanelLayout);
                HeaderPanelLayout.setHorizontalGroup(
                                HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 1251, Short.MAX_VALUE));
                HeaderPanelLayout.setVerticalGroup(
                                HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 56, Short.MAX_VALUE));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Navbar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(HeaderPanel,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(Navbar,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(HeaderPanel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addContainerGap()));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void hideAllPanels() {
                managerUser.setVisible(false);
                Revenue.setVisible(false);
                Profile.setVisible(false);
        }

        private void switchPanel(String panelName) {
                hideAllPanels();
                switch (panelName) {
                        case "managerUser":
                                managerUser.setVisible(true);
                                break;
                        case "Revenue":
                                Revenue.setVisible(true);
                                break;
                        case "Profile":
                                Profile.setVisible(true);
                                break;
                        default:
                                break;
                }
        }

        private void UpdateInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {
                switchPanel("Profile");
        }

        private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {
                switchPanel("managerUser");
        }

        private void RevenueButtonActionPerformed(java.awt.event.ActionEvent evt) {
                switchPanel("Revenue");
        }

        private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("Sign out action performed");

        }

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel HeaderPanel;
        private javax.swing.JPanel Navbar;
        private javax.swing.JButton RevenueButton;
        private javax.swing.JButton SignOutButton;
        private javax.swing.JButton UpdateInfoButton;
        private javax.swing.JButton UserButton;
        // End of variables declaration//GEN-END:variables
}
