/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store.view.employee.publisher;

import store.Model.Publisher;
import store.Service.BookService;

/**
 *
 * @author bourbon
 */
public class EditPublisher extends javax.swing.JFrame {

    private BookService bookService;
    private int publisherID;

    public EditPublisher(int publisherID) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.bookService = new BookService();
        this.publisherID = publisherID; // Set the bookId before loading details
        load();
    }

    public void load() {
        try {
            Publisher publisher = bookService.selectPublisher(publisherID);
            if (publisher != null) {
                ID.setText(String.valueOf(publisher.getPublisherID()));
                InputName.setText(publisher.getPublisherName());
                if (publisher.getStatus()) {
                    Active.setSelected(true);
                } else {
                    InActice.setSelected(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * his method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        CancelButton = new javax.swing.JButton();
        InActice = new javax.swing.JRadioButton();
        Active = new javax.swing.JRadioButton();
        ID = new javax.swing.JTextField();
        InputName = new javax.swing.JTextField();
        SatusLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(InActice);
        InActice.setText("InActice");

        buttonGroup1.add(Active);
        Active.setText("Active");

        ID.setEditable(false);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        InputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNameActionPerformed(evt);
            }
        });

        SatusLabel.setText("Status");

        NameLabel.setText("Name");

        IDLabel.setText("ID");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SatusLabel)
                                        .addComponent(NameLabel)
                                        .addComponent(IDLabel))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(Active)
                                                .addGap(18, 18, 18)
                                                .addComponent(InActice))
                                        .addComponent(ID)
                                        .addComponent(InputName))
                                .addContainerGap(211, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelButton)
                                .addGap(29, 29, 29)
                                .addComponent(OKButton)
                                .addGap(33, 33, 33)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(IDLabel)
                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NameLabel)
                                        .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SatusLabel)
                                        .addComponent(Active)
                                        .addComponent(InActice))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CancelButton)
                                        .addComponent(OKButton))
                                .addGap(42, 42, 42)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_CancelButtonActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_IDActionPerformed

    private void InputNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_InputNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_InputNameActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_OKButtonActionPerformed
        try {
            String name = InputName.getText();
            boolean status = Active.isSelected();
            if (name.isEmpty()) {
                throw new Exception("Name is required");
            }
            Publisher publisher = new Publisher(publisherID, name, status);
            bookService.updatePublisher(publisher);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }// GEN-LAST:event_OKButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Active;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JRadioButton InActice;
    private javax.swing.JTextField InputName;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel SatusLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
